[build-system]
requires = [
    "setuptools>=77.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["vnrecode", "unrenapk", "vnds2renpy", "rpatool"]
include-package-data = true

[tool.setuptools.package-data]
'vnrecode' = ['*.py']
'vnds2renpy' = ['*.py']
'unrenapk' = ['*.py']
'rpatool' = ['*.py']

[project.scripts]
vnrecode = "vnrecode.__main__:init"
vnds2renpy = "vnds2renpy.__main__:main"
unrenapk = "unrenapk.application:launch"
rpatool = "rpatool.rpatool:main"

[project]
name = "vntools"
version = "2.1-dev"
requires-python = ">= 3.11"
dependencies = [
    "Pillow>=12.1.0",
    "python-ffmpeg>=2.0.12",
    "progress>=1.6",
    "colorama>=0.4.6"
]